### ISSUE TITLE
The folder combobox in the Credential Dialog is expandable even if edit is disabled, causing an error

### ISSUE THREAD

**Issue by LightJack05** [Jannik-Hm/AnonKey-Frontend#61]
Platform: Linux Desktop (6.12.7-arch1-1; Wayland (Hyprland))

If a credential is opened, even while not in edit mode, you can expand the combobox selection menu, but not select a value.

If you select a value in the combobox while not in edit mode, then enter into edit mode, and then change the value and save, it seems to cause an error sometimes. See stacktrace:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: setState() called after dispose(): _CredentialListWidget#7542d(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1168:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1203:6)
#2      _CredentialListWidget._fromList.<anonymous closure> (package:anonkey_frontend/src/Credentials/credential_list_view.dart:48:9)
#3      _CredentialDetailWidget.build.save (package:anonkey_frontend/src/Credentials/list-entry/credential_detail_view.dart:143:68)
<asynchronous suspension>
#4      _CredentialDetailWidget.build.<anonymous closure>.<anonymous closure> (package:anonkey_frontend/src/Credentials/list-entry/credential_detail_view.dart:247:25)
<asynchronous suspension>
```

I cant reproduce it reliably. May be a race condition?

**Comment by Jannik-Hm** [comment]
Might have to wrap the DropdownButton inside of a `IgnorePointer` as the official way for disabling seems to be buggy
